services:
  next_app:
    build:
      context: .
      target: production
    env_file:
      - ./.env
    environment:
      - NODE_ENV=PROD

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node_app
  
