services:
  next_app:
    image: devimage
    build:
      context: .
      target: production
    env_file:
      - ./.env
    environment:
      - NODE_ENV=PROD
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 1s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next_app
